# Generated by Django 6.0.7 on 2026-07-17 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slugf',
            new_name='slug',
        ),
    ]
